# Reddit Scraper Configuration
reddit:
  subreddit: "creepypasta"
  allowed_flairs:
    - "Text Story"
    - "Very Short Story"
  sort_by: "top"  # hot, new, top, rising
  time_filter: "all"  # hour, day, week, month, year, all
  limit: 10

# Text-to-Speech Configuration
tts:
  provider: "elevenlabs"  # gtts, openai, azure, elevenlabs
  language: "en"
  slow: false
  
  # OpenAI TTS settings (if using OpenAI)
  openai:
    model: "tts-1-hd"
    voice: "onyx"  # alloy, echo, fable, onyx, nova, shimmer
    
  # Azure TTS settings (if using Azure)
  azure:
    voice: "en-US-AriaNeural"
    rate: "+0%"
    pitch: "+0Hz"
    
  # ElevenLabs TTS settings (if using ElevenLabs)
  elevenlabs:
    model: "eleven_multilingual_v2"  # eleven_monolingual_v1, eleven_multilingual_v2, eleven_turbo_v2
    voice: "3SF4rB1fGBMXU9xRM7pz"   # Rachel (creepy/dramatic voice)
    stability: 0.75
    similarity_boost: 0.5
    style: 0.0
    use_speaker_boost: true

# Audio Configuration
audio:
  output_format: "mp3"
  quality: "high" 
  volume:
    narration: 0.8  # Clear narration volume
    background_music: 0.4  # Very low volume for subtle background ambiance
  
  # Background music settings
  background_music:
    enabled: true
    fade_in_duration: 2.0
    fade_out_duration: 2.0
    loop: true

# Story Processing
story:
  min_length: 100  # Minimum characters
  max_length: 5000  # Maximum characters
  # Story Processing
story:
  min_length: 100  # Minimum characters
  max_length: 5000  # Maximum characters
  clean_text: true
  remove_markdown: true
  
# Video Configuration
video:
  enabled: true
  resolution:
    width: 1920
    height: 1080
  fps: 30
  image_duration: 10  # seconds per image
  transition_duration: 1.0  # seconds for crossfade transition
  
  # Image generation settings
  images:
    count: 6  # Number of images to generate per story
    style: "kid_friendly_horror"  # Horror but suitable for children
    quality: "hd"  # standard or hd
    size: "1792x1024"  # DALL-E 3 size options: 1024x1024, 1792x1024, 1024x1792
    cache_enabled: true
      # Background music mixing
  background_music:
    volume: 0.4  # Much lower volume for subtle background ambiance
    fade_in_duration: 3.0
    fade_out_duration: 3.0
      # Subtitle settings
  subtitles:
    enabled: true  # Enable subtitle generation and overlay
    font_size: 24  # Font size for subtitles
    font_color: "white"  # Font color (white, yellow, etc.)
    outline_color: "black"  # Outline color for better readability
    outline_width: 2  # Outline width in pixels
    position: "bottom"  # Position: bottom, top, center
    max_chars_per_line: 50  # Maximum characters per subtitle line
    words_per_subtitle: 8  # Words per subtitle segment
    
  # Output settings
  output:
    directory: "assets/videos"
    format: "mp4"
    codec: "libx264"
    audio_codec: "aac"
    bitrate: "2000k"

# Output Settings
output:
  directory: "assets/output"
  filename_format: "{title}_{timestamp}"
  create_video: true  # Enable video creation
  
# API Keys (set via environment variables)
# OPENAI_API_KEY - Required for image generation
  
# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/creepypasta_ai.log"
